"""
Regression vectors from REAL Mode 1 CMS producers (AUD-F78/F79/F80/F82).

fixtures/mode1_real_cms_producer_vectors.json was generated by
rfc/070_publication_push/evidence/mode1_strict_cms_profile_and_path_real_producers/
run_real_cms_producers_against_strict_verifier.py (2026-09-24): the Python SDK
and Node SDK CMS builders, and `openssl cms -sign -noattr` (OpenSSL 3.0.13)
with issuerAndSerialNumber and -keyid signer identifiers. OpenSSL writes the
certificates SET OF in DER-sorted order ([root, intermediate, leaf] here),
which the positional chain walker used to reject (AUD-F80); its RS256
SignerInfo uses rsaEncryption (OWN-021). Public material only; certificates
are valid for a century around the fixed reference time.

Six BouncyCastle 1.78.1 (Java) vectors were appended locally on 2026-09-24 by
the same script with --bouncycastle-jars: CMSSignedData.getEncoded() default
(BER with indefinite lengths) and getEncoded("DER"). RFC 5652 CMS is BER, so
both verify (OWN-024, Chris 2026-09-24: accept BER).
"""

import base64
import json
import os

import pytest
from cryptography import x509

from hw_attest_verify import verify_hardware_attestation

_VECTORS_PATH = os.path.join(os.path.dirname(__file__), "fixtures", "mode1_real_cms_producer_vectors.json")
with open(_VECTORS_PATH, encoding="utf-8") as _vectors_file:
  _VECTORS = json.load(_vectors_file)


@pytest.mark.parametrize("vector", _VECTORS, ids=[vector["name"] for vector in _VECTORS])
def test_real_producer_vector_verifies_as_the_draft_requires(vector):
  result = verify_hardware_attestation(
    header_value=vector["header_value"],
    email_headers=vector["email_headers"],
    body=base64.b64decode(vector["body_base64"]),
    trusted_root_certificates=[x509.load_pem_x509_certificate(vector["trusted_root_pem"].encode())],
    reference_time_unix=vector["reference_time_unix"],
  )
  assert result.is_valid == vector["expected_valid"], result.failure_reasons


def test_vectors_cover_every_producer_and_algorithm():
  assert {vector["producer"] for vector in _VECTORS} >= {
    "python-sdk", "node-sdk", "openssl", "openssl-keyid", "openssl-set-order-leaf-root-intermediate",
    "bouncycastle-default-ber", "bouncycastle-der"}
  assert any(vector["header_value"].split("chain=")[1].startswith("MIA") for vector in _VECTORS)  # BER: 30 80 ...
  assert {vector["alg"] for vector in _VECTORS} == {"ES256", "RS256", "PS256"}
  assert any(not vector["expected_valid"] for vector in _VECTORS)  # the PSS salt-20 negative
